spring:
  application:
    name: MusicSheets
  banner:
    location: banner.txt

  datasource:
    url: jdbc:postgresql://localhost:5432/music_sheets
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

logging:
  pattern:
    console: "%date  %clr(%-5level) [%12.12thread] %cyan(%-40.40logger{40}) : %msg %n"
    file: "%date | %-5level | [%12.12thread] | %-40.40logger{40} : %msg %n"
  level:
    org.example.musicsheets: info
  file:
    name: logs/application.log

security:
  jwt:
    secret-key: f73b7fbcc58da11bcb329382e25fb3525aaa16c5ffce972715bb3d1c7bca287d
    expiration-time: 3600000  #1 hour